import os
nome=input("Digite seu nome:")
cpf=input("Digite seu cpf:")
rg=input("Digite seu rg:")
nasc=int(input("Digite seu nascimento:"))
sexo=input("Digite seu sexo:")
peso=int(input("Digite seu peso:"))
sang=(input("Digite seu tipo sanguineo:"))
renda=int(input("Digite sua renda:"))
endereço=(input("Digite seu endereço:"))
tel=int(input("Digite seu telefone:"))
cidade=(input("Digite seu cidade:"))
estado=(input("Digite seu estado:"))

print ("+---------------------------------------------+")
print ("|                 Relatorio                   |")
print ("|                                             |")
print(f"| Nome:{nome}                                 |")
print ("|                                             |")
print(f"| Cpf:{cpf}                                   |")
print ("|                                             |")
print(f"| Rg:{rg}                                     |")
print ("|                                             |")
print(f"| Data de nascimento:{nasc}                   |")
print ("|                                             |")
print(f"| Sexo:{sexo}                                 |")
print ("|                                             |")
print(f"| Peso:{peso}                                 |")
print ("|                                             |")
print(f"| Tipo sanguineo:{sang}                       |")
print ("|                                             |")
print(f"| Renda:{renda}                               |")
print ("|                                             |")
print(f"| Endereço:{endereço}                         |")
print ("|                                             |")
print(f"| telefone:{tel}                              |")
print ("|                                             |")
print(f"| Cidade:{cidade}                             |")
print ("|                                             |")
print(f"| Estado:{estado}                             |")
print ("|                                             |")
print ("+---------------------------------------------+")